export const artists = [
  {
    id: "ines-alarcon",
    name: "Ines Alarcon",
    specialty: "Abstraccion mineral y gesto organico",
    bio:
      "Artista visual enfocada en capas translucidas, pigmentos minerales y composiciones silenciosas para espacios residenciales y hospitality.",
  },
  {
    id: "marco-soler",
    name: "Marco Soler",
    specialty: "Geometria arquitectonica",
    bio:
      "Su obra estudia proporciones, ritmos de fachada y color sobrio, con piezas pensadas para dialogar con arquitectura contemporanea.",
  },
  {
    id: "lucia-vidal",
    name: "Lucia Vidal",
    specialty: "Paisaje abstracto y atmosfera",
    bio:
      "Trabaja grandes campos cromaticos inspirados en horizonte, luz y memoria; ideal para interiores calmos y envolventes.",
  },
  {
    id: "nadir-reyes",
    name: "Nadir Reyes",
    specialty: "Textura, sombra y materia",
    bio:
      "Explora superficies tactiles, negros suaves y contraste material para hoteles, restaurantes y proyectos de autor.",
  },
];

const materials = [
  "Canvas",
  "Fine art print",
  "Framed canvas",
  "Optional acoustic panel version",
];

export const artworks = [
  {
    id: "arena-suspendida",
    title: "Arena suspendida",
    artistId: "ines-alarcon",
    mainSize: "180 x 120 cm",
    price: "Cotizar",
    orientation: "Horizontal",
    style: "Organico",
    colors: "Neutros",
    roomType: "Living room",
    sizes: ["140 x 100 cm", "180 x 120 cm", "240 x 160 cm"],
    materials,
    description:
      "Capas suaves de arena, blanco calido y lineas gestuales para muros amplios con luz natural.",
    suggestedRooms: ["Living room", "Bedroom", "Hotel lobby", "Office"],
    finish: "Mate satinado",
    printing: "Pigmentos minerales de alta permanencia",
    installation: "Bastidor oculto con nivelacion profesional",
    palette: ["#efe6d8", "#c9ad8d", "#f7f2e8", "#8f7b67"],
  },
  {
    id: "nocturno-claro",
    title: "Nocturno claro",
    artistId: "nadir-reyes",
    mainSize: "200 x 140 cm",
    price: "Cotizar",
    orientation: "Horizontal",
    style: "Textural",
    colors: "Oscuros",
    roomType: "Restaurant",
    sizes: ["160 x 110 cm", "200 x 140 cm", "260 x 180 cm"],
    materials,
    description:
      "Negros lavados, carbon y veladuras profundas para interiores gastronomicos y lobbies sobrios.",
    suggestedRooms: ["Restaurant", "Hotel lobby", "Office"],
    finish: "Mate profundo",
    printing: "Fine art giclee sobre lienzo premium",
    installation: "Riel frances o bastidor flotante",
    palette: ["#1d1c1b", "#3a3836", "#9d9489", "#d8d0c4"],
  },
  {
    id: "trazo-de-luz",
    title: "Trazo de luz",
    artistId: "lucia-vidal",
    mainSize: "150 x 210 cm",
    price: "Cotizar",
    orientation: "Vertical",
    style: "Atmosferico",
    colors: "Calidos",
    roomType: "Hotel lobby",
    sizes: ["120 x 170 cm", "150 x 210 cm", "180 x 260 cm"],
    materials,
    description:
      "Un campo luminoso vertical que eleva vestibulos, dobles alturas y espacios de recepcion.",
    suggestedRooms: ["Hotel lobby", "Living room", "Office"],
    finish: "Mate con proteccion UV",
    printing: "12 tintas de archivo sobre canvas",
    installation: "Anclaje reforzado para gran formato",
    palette: ["#f0c979", "#f6ead2", "#b97c50", "#fffaf0"],
  },
  {
    id: "modulo-ix",
    title: "Modulo IX",
    artistId: "marco-soler",
    mainSize: "220 x 150 cm",
    price: "Cotizar",
    orientation: "Horizontal",
    style: "Geometrico",
    colors: "Neutros",
    roomType: "Office",
    sizes: ["160 x 110 cm", "220 x 150 cm", "300 x 200 cm"],
    materials,
    description:
      "Geometria editorial, balance y silencios amplios para oficinas, estudios y arquitectura minimalista.",
    suggestedRooms: ["Office", "Hotel lobby", "Living room"],
    finish: "Canvas mate tensado",
    printing: "Alta definicion con perfil cromatico certificado",
    installation: "Separadores ocultos o bastidor",
    palette: ["#eeeae1", "#242424", "#a59b8e", "#d1c5b7"],
  },
  {
    id: "jardin-en-calma",
    title: "Jardin en calma",
    artistId: "ines-alarcon",
    mainSize: "180 x 180 cm",
    price: "Cotizar",
    orientation: "Cuadrada",
    style: "Organico",
    colors: "Verdes",
    roomType: "Bedroom",
    sizes: ["120 x 120 cm", "180 x 180 cm", "220 x 220 cm"],
    materials,
    description:
      "Verdes apagados y materia vegetal abstracta para habitaciones, spas y espacios de descanso.",
    suggestedRooms: ["Bedroom", "Living room", "Hotel lobby"],
    finish: "Mate natural",
    printing: "Pigmento acuoso de archivo",
    installation: "Bastidor reforzado",
    palette: ["#dfe7dc", "#7d8b6f", "#304339", "#b8b497"],
  },
  {
    id: "umbral-terracota",
    title: "Umbral terracota",
    artistId: "lucia-vidal",
    mainSize: "240 x 160 cm",
    price: "Cotizar",
    orientation: "Horizontal",
    style: "Atmosferico",
    colors: "Terracota",
    roomType: "Restaurant",
    sizes: ["180 x 120 cm", "240 x 160 cm", "320 x 210 cm"],
    materials,
    description:
      "Un horizonte terroso de gran escala para restaurantes, terrazas cubiertas y casas de playa.",
    suggestedRooms: ["Restaurant", "Living room", "Hotel lobby"],
    finish: "Mate satinado",
    printing: "Giclee premium con barniz protector",
    installation: "Instalacion mural con plantilla",
    palette: ["#b85f43", "#e9c7a3", "#fff4e4", "#6f4637"],
  },
  {
    id: "ritmo-de-piedra",
    title: "Ritmo de piedra",
    artistId: "marco-soler",
    mainSize: "160 x 220 cm",
    price: "Cotizar",
    orientation: "Vertical",
    style: "Geometrico",
    colors: "Grises",
    roomType: "Office",
    sizes: ["120 x 170 cm", "160 x 220 cm", "200 x 280 cm"],
    materials,
    description:
      "Bloques, sombra y proporcion vertical para muros estrechos o circulaciones arquitectonicas.",
    suggestedRooms: ["Office", "Hotel lobby", "Living room"],
    finish: "Fine art mate",
    printing: "Papel algodon o canvas de archivo",
    installation: "Marco flotante opcional",
    palette: ["#eeeeea", "#bbb6ad", "#696865", "#282828"],
  },
  {
    id: "marea-blanca",
    title: "Marea blanca",
    artistId: "ines-alarcon",
    mainSize: "260 x 170 cm",
    price: "Cotizar",
    orientation: "Horizontal",
    style: "Minimal",
    colors: "Blancos",
    roomType: "Living room",
    sizes: ["180 x 120 cm", "260 x 170 cm", "340 x 220 cm"],
    materials,
    description:
      "Textura casi monocroma con relieve visual para interiores donde la luz y el mobiliario son protagonistas.",
    suggestedRooms: ["Living room", "Bedroom", "Office"],
    finish: "Blanco mate textural",
    printing: "Canvas de trama fina",
    installation: "Bastidor oculto",
    palette: ["#fffdf8", "#f0ede6", "#d5d0c7", "#b5aa9e"],
  },
  {
    id: "azul-profundo",
    title: "Azul profundo",
    artistId: "nadir-reyes",
    mainSize: "190 x 130 cm",
    price: "Cotizar",
    orientation: "Horizontal",
    style: "Textural",
    colors: "Azules",
    roomType: "Bedroom",
    sizes: ["150 x 100 cm", "190 x 130 cm", "250 x 170 cm"],
    materials,
    description:
      "Azules de baja saturacion y veladuras densas para dormitorios, suites y salones privados.",
    suggestedRooms: ["Bedroom", "Hotel lobby", "Office"],
    finish: "Mate profundo",
    printing: "Pigmentos de archivo sobre lienzo",
    installation: "Sistema nivelado de baja separacion",
    palette: ["#172332", "#2e5366", "#8aa1a9", "#e7e4dc"],
  },
  {
    id: "linea-habitable",
    title: "Linea habitable",
    artistId: "marco-soler",
    mainSize: "210 x 210 cm",
    price: "Cotizar",
    orientation: "Cuadrada",
    style: "Geometrico",
    colors: "Calidos",
    roomType: "Hotel lobby",
    sizes: ["150 x 150 cm", "210 x 210 cm", "260 x 260 cm"],
    materials,
    description:
      "Composicion modular de gran presencia para proyectos contract y residencias de lenguaje sobrio.",
    suggestedRooms: ["Hotel lobby", "Office", "Living room"],
    finish: "Canvas mate",
    printing: "Tintas pigmentadas de alta definicion",
    installation: "Anclaje profesional incluido en cotizacion",
    palette: ["#f5eee2", "#d0aa78", "#7d6b58", "#201f1d"],
  },
  {
    id: "silencio-dorado",
    title: "Silencio dorado",
    artistId: "lucia-vidal",
    mainSize: "170 x 240 cm",
    price: "Cotizar",
    orientation: "Vertical",
    style: "Minimal",
    colors: "Dorados",
    roomType: "Living room",
    sizes: ["130 x 190 cm", "170 x 240 cm", "210 x 300 cm"],
    materials,
    description:
      "Una pieza vertical de luz tenue, pensada para escaleras, recibidores y muros protagonistas.",
    suggestedRooms: ["Living room", "Hotel lobby", "Restaurant"],
    finish: "Mate con acento perlado",
    printing: "Giclee de archivo",
    installation: "Bastidor reforzado para altura",
    palette: ["#f5dfaa", "#fff6de", "#aa7f3c", "#77634a"],
  },
  {
    id: "sombra-vegetal",
    title: "Sombra vegetal",
    artistId: "nadir-reyes",
    mainSize: "230 x 150 cm",
    price: "Cotizar",
    orientation: "Horizontal",
    style: "Organico",
    colors: "Verdes",
    roomType: "Restaurant",
    sizes: ["170 x 110 cm", "230 x 150 cm", "300 x 195 cm"],
    materials,
    description:
      "Contrastes de hoja, sombra y gesto pictorico para restaurantes, bares boutique y espacios tropicales.",
    suggestedRooms: ["Restaurant", "Hotel lobby", "Living room"],
    finish: "Mate protegido",
    printing: "Canvas premium con barniz UV",
    installation: "Montaje oculto o panel acustico",
    palette: ["#22372c", "#5c765f", "#d9d0bd", "#111614"],
  },
];
